
version: 2

models:
  # - name: my_first_dbt_model
  #   description: "A starter dbt model"
  #   columns:
  #     - name: id
  #       description: "The primary key for this table"
  #       tests:
  #         - unique
  #         - not_null
  #
  # - name: my_second_dbt_model
  #   description: "A starter dbt model"
  #   columns:
  #     - name: id
  #       description: "The primary key for this table"
  #       tests:
  #         - unique
  #         - not_null

  - name: Milestone1
    description: "Milestone1"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: Milestone2
    description: "Milestone2"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: Milestone3
    description: "Milestone3"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: Milestone4
    description: "Milestone4"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: Milestone5
    description: "Milestone5"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
